# Generated by Django 6.0.6 on 2026-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Human Resources', 'Human Resources'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Design', 'Design')], max_length=50, verbose_name='Department')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary (USD)')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'ordering': ['-date_of_joining'],
            },
        ),
    ]
